Mvc_ESM/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using System.Collections;
using Mvc_ESM.Static_Helper;

namespace Mvc_ESM.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TeacherController : Controller
    {
        // GET: /GiaoVien/
        [HttpGet]
        public ViewResult Index()
        {
            var giaoviens = (from m in InputHelper.db.giaoviens
                             select m
                           ).Include(m => m.bomon);
            InitViewBag(false);
            return View(giaoviens.ToList());
        }

        [HttpPost]
        public ViewResult Index(String Khoa, String BoMon, String SearchString)
        {
            var giaoviens = (from m in InputHelper.db.giaoviens
                             where ((BoMon == "" && m.bomon.KhoaQL.Equals(Khoa)) || (BoMon != "" && m.bomon.MaBoMon.Equals(BoMon))) && ((m.HoLot + " " + m.TenGiaoVien).Contains(SearchString) || SearchString == "")
                             select m
                           ).Include(m => m.bomon);
            InitViewBag(true, Khoa);
            return View(giaoviens.ToList());
        }

        private void InitViewBag(Boolean IsPost, string Khoa = "")
        {
            var KhoaQry = from d in InputHelper.db.khoas
                          orderby d.TenKhoa
                          select new { MaKhoa = d.MaKhoa, TenKhoa = d.TenKhoa };
            ViewBag.Khoa = new SelectList(KhoaQry.ToArray(), "MaKhoa", "TenKhoa");
                
            var BoMonQry = from b in InputHelper.db.bomons
                           where b.khoa.MaKhoa == (IsPost ? Khoa : KhoaQry.FirstOrDefault().MaKhoa)
                           select new { MaBoMon = b.MaBoMon, TenBoMon = b.TenBoMon };
            ViewBag.BoMon = new SelectList(BoMonQry.ToArray(), "MaBoMon", "TenBoMon");
            ViewBag.SearchString = "";
        }
    }
}

Mvc_ESM/Views/Teacher/Index.cshtml
@model IEnumerable<Model.giaovien>
@{
    ViewBag.Title = "Giáo viên";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Index", "Teacher", FormMethod.Post, new { @id = "FilterForm" }))
{
    <p>
        <p>
            Khoa: @Html.DropDownList("Khoa", ViewBag.Khoa as SelectList, new { id = "KhoaList" })
            Bộ môn: @Html.DropDownList("BoMon", ViewBag.BoMon as SelectList, Mvc_ESM.Settings.Page.Settings.SelectAllString, new { id = "BoMonList" })
            Tên: @Html.TextBox("SearchString", ViewBag.SearchString as string, new { id = "SearchString" })
            <input type="submit" value="Thực hiện" />
        </p>

    </p>
}

<table id="table">
    <thead>
        <tr>
            <th>Mã giáo viên
            </th>
            <th>Họ lót
            </th>
            <th>Tên giáo viên
            </th>
            <th>Bộ môn
            </th>
            <th>Học hàm
            </th>
            <th>Học vị
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MaGiaoVien)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoLot)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenGiaoVien)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.bomon.TenBoMon)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HocHam)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.HocVi)
                </td>
            </tr>
        }
    </tbody>
</table>

@Html.Partial("_DataTable.Lib")

<script type="text/javascript" charset="utf-8">
    $("#KhoaList").change(function () {
        var id = $(this).val();
        $.getJSON("/Services/LoadSubjectsByFacultyID", { FacultyID: id },
        function (Data) {
            var select = $("#BoMonList");
            select.empty();
            select.append($('<option/>', {
                value: "",
                text: "@Mvc_ESM.Settings.Page.Settings.SelectAllString"
            }));
            $.each(Data, function (index, itemData) {
                select.append($('<option/>', {
                    value: itemData.Value,
                    text: itemData.Text
                }));
            });
            $("#SearchString").empty();
        });
    });

    var oTable = $('#table').dataTable({
        @Html.Partial("_DataTable")
    });

    new FixedHeader(oTable);

</script>